default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: chat-parisrb_development

test:
  <<: *default
  database: chat-parisrb_test

production:
  <<: *default
  database: chat-parisrb
  username: chat-parisrb
  password: <%= ENV['CHAT-PARISRB_DB_PASSWORD'] %>
